### ISSUE TITLE
Is there any ways for generating RGBD dataset from 3D-FRONT?

### ISSUE THREAD

**Issue by nobodypengium** [3D-FRONT-FUTURE/3D-FRONT-ToolBox#9]

**Comment by nobodypengium** [comment]
I got something like this
![image](https://user-images.githubusercontent.com/13833330/112863953-f6f58f80-90e9-11eb-95ca-023f14c5614b.png)

**Comment by yizhouzhao** [comment]
https://github.com/alibaba/Trescope/issues/1

**Comment by hit-lyf** [comment]
Traceback (most recent call last):
  File "/export4/Datasets/room/3D_Floor/3D-FRONT-ToolBox-master/scripts/render.py", line 237, in <module>
    camera = AdaptedCameras(os.path.join(json_path, scene+'.json'))
  File "/export4/Datasets/room/3D_Floor/3D-FRONT-ToolBox-master/adapted.py", line 16, in __init__
    self.initialize()
  File "/export4/Datasets/room/3D_Floor/3D-FRONT-ToolBox-master/adapted.py", line 21, in initialize
    self.floor_info = get_floor_info(self.scene_file)
AttributeError: 'NoneType' object has no attribute 'dict_instance_for_furniture'
我遇到了这个问题，self.scene_content = read_scene_json(self.scene_file)读取场景json返回None，请问您知道是什么原因吗
